module.exports = {
  docs: {
    Introduction: [
      'introduction/getting-started',
      'introduction/installation',
      'introduction/features',
      'introduction/motivation',
      'introduction/new-in-2',
    ],
    CLI: ['cli/config', 'cli/codegen', 'cli/javascript', 'cli/programmatic'],
    React: [
      'react/basic-usage',
      'react/caveats',
      'react/config',
      'react/query',
      'react/mutations',
      'react/subscriptions',
      'react/suspense',
      'react/meta',
      'react/ssr',
      'react/api-reference',
      {
        type: 'category',
        label: 'API Reference',
        items: require('./sidebars/react.js'),
      },
    ],
    Core: [
      'core/basic-usage',
      'core/helpers',
      'core/config',
      'core/mutations',
      'core/subscriptions',
      'core/persistence',
      'core/graphql-upload',
      {
        type: 'category',
        label: 'API Reference',
        items: require('./sidebars/core.js'),
      },
    ],
    'Development Tools': ['development/logger'],
    FAQ: ['faq', 'contributing'],
  },
};
