module.exports = [
  'core/api/index',
  'core/api/modules',
  {
    type: 'category',
    label: 'Enumerations',
    items: ['core/api/enums/selectiontype'],
  },
  {
    type: 'category',
    label: 'Classes',
    items: [
      'core/api/classes/eventhandler',
      'core/api/classes/selection',
      'core/api/classes/gqlesserror',
    ],
  },
  {
    type: 'category',
    label: 'Interfaces',
    items: [
      'core/api/interfaces/accessorcache',
      'core/api/interfaces/assignselections',
      'core/api/interfaces/buildandfetchselections',
      'core/api/interfaces/buildselection',
      'core/api/interfaces/clientoptions',
      'core/api/interfaces/gqlessclient',
      'core/api/interfaces/hydratecache',
      'core/api/interfaces/hydratecacheoptions',
      'core/api/interfaces/innerclientstate',
      'core/api/interfaces/interceptormanager',
      'core/api/interfaces/mutate',
      'core/api/interfaces/mutatehelpers',
      'core/api/interfaces/parseschematypeinfo',
      'core/api/interfaces/prefetch',
      'core/api/interfaces/preparerender',
      'core/api/interfaces/refetch',
      'core/api/interfaces/resolveoptions',
      'core/api/interfaces/resolved',
      'core/api/interfaces/resolvers',
      'core/api/interfaces/retryconfigstate',
      'core/api/interfaces/scalars',
      'core/api/interfaces/scheduler',
      'core/api/interfaces/schema',
      'core/api/interfaces/selectionmanager',
      'core/api/interfaces/setcache',
      'core/api/interfaces/subscribeevents',
      'core/api/interfaces/subscriptionsclient',
      'core/api/interfaces/type',
    ],
  },
];
