module.exports = [
  'react/api/index',
  'react/api/modules',
  {
    type: 'category',
    label: 'Interfaces',
    items: [
      'react/api/interfaces/createreactclientoptions',
      'react/api/interfaces/graphqlhoc',
      'react/api/interfaces/graphqlhocoptions',
      'react/api/interfaces/metastate',
      'react/api/interfaces/preparequery',
      'react/api/interfaces/preparereactrender',
      'react/api/interfaces/preparedquery',
      'react/api/interfaces/reactclient',
      'react/api/interfaces/reactclientdefaults',
      'react/api/interfaces/usegqlessstateoptions',
      'react/api/interfaces/usehydratecache',
      'react/api/interfaces/usehydratecacheoptions',
      'react/api/interfaces/uselazyquery',
      'react/api/interfaces/uselazyqueryoptions',
      'react/api/interfaces/uselazyquerystate',
      'react/api/interfaces/usemetastate',
      'react/api/interfaces/usemutation',
      'react/api/interfaces/usemutationoptions',
      'react/api/interfaces/usemutationstate',
      'react/api/interfaces/usepreparedqueryoptions',
      'react/api/interfaces/usequery',
      'react/api/interfaces/usequeryoptions',
      'react/api/interfaces/usequerystate',
      'react/api/interfaces/userefetch',
      'react/api/interfaces/userefetchoptions',
      'react/api/interfaces/userefetchstate',
      'react/api/interfaces/usesubscription',
      'react/api/interfaces/usetransactionquery',
      'react/api/interfaces/usetransactionquerystate',
    ],
  },
];
